### ISSUE TITLE
create-react-app IE11 Unhandled promise rejection

### ISSUE THREAD

**Issue by franklinhardt** [apexcharts/react-apexcharts#137]
I can't get react-apexchart working on IE11. In a new create-react-app installation with:

import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';

to make create-react-app work on IE11 I copied the Example code for a simple bar chart provided here on GitHub and I get:

_Unhandled promise rejection TypeError: Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden._

or translated:

_“Unable to get property 'add' of undefined or null reference”_

the same error occurs with all kinds of properties on hovering the chart (i.e. when hovering the legend the error “Unable to get property 'contains' of undefined or null reference” points to apexcharts.common.js (7783,1) )

excerpt from developer tools:
      [functions]: ,
      __proto__: { },
      description: "Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      message: "Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.

**Comment by aselcuk** [comment]
same issue
![err](https://user-images.githubusercontent.com/41209531/75849704-93ba0080-5df6-11ea-8945-490a029811b4.PNG)

**Comment by sarathcs** [comment]
@unfunk77, This occurs due to absence of "classList" (of Html Element)property on SVGRectElement, which is being used in the "drawRect" of Graphics method in IE 11. So, as the [documentation](https://www.npmjs.com/package/apexcharts#using-it-with-ie11) says, we are to use the classList polyfill from "https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill". Specifically for the create-react-app, we have to use (as you mentioned) - 

import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';

and this classList polyfill in index.html. 

That should solve it.

**Comment by SandeepKapalawai** [comment]
Hi @sarathcs  @unfunk77 
I do have the similar issue in IE 11,  i am using radial bar charts in my  create react application
But  i see in IE 11 the charts are rendering but the color fill is not happening.

As mentioned in the documentation and as per above @sarathcs  comments, i have include those polyfills in my index.html file as below :

` <script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill"></script>
     <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"></script>S
    <title>React App</title>`

and in my index.js file i have inlcude below polyfills 

`
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';`

But i still didnt see it is loading correctly in IE, is there anything i am missing or any thing to be corrected ?

Thank you

**Comment by unfunk77** [comment]
Hi Sandeep,

on the carecreations website we have the following snippet included in the html head toinclude the IE11 ployfills needed for the emolient jockey:

<script>
        window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"><\/script>'), window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill@1.2.20171210/classList.min.js"><\/script>'), window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"><\/script>')
    </script>

hope thie helps,

best regards,
Frank



________________________________
Von: Sandeep Kapalawai <notifications@github.com>
Gesendet: Mittwoch, 28. Oktober 2020 03:58
An: apexcharts/react-apexcharts <react-apexcharts@noreply.github.com>
Cc: Frank Linhardt <frank.linhardt@qwaiko.de>; Mention <mention@noreply.github.com>
Betreff: Re: [apexcharts/react-apexcharts] create-react-app IE11 Unhandled promise rejection (#137)


Hi @sarathcs<https://github.com/sarathcs> @unfunk77<https://github.com/unfunk77>
I do have the similar issue in IE 11, i am using radial bar charts in my create react application
But i see in IE 11 the charts are rendering but the color fill is not happening.

As mentioned in the documentation and as per above @sarathcs<https://github.com/sarathcs> comments, i have include those polyfills in my index.html file as below :

<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill"></script> <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"></script>S <title>React App</title>

and in my index.js file i have inlcude below polyfills

import 'react-app-polyfill/ie11'; import 'react-app-polyfill/stable';

But i still didnt see it is loading correctly in IE, is there anything i am missing or any thing to be corrected ?

Thank you

**Comment by SandeepKapalawai** [comment]
Hi @unfunk77 ,

Thanks for the reply , i have tried the same by including in my index.html file. looks like the issue still persists, there was an error in IE 11 ' **Unhandled promise rejection TypeError: Unable to get property 'add' of undefined or null reference**'

Looks like you went through the same issue , how did you get these resolved.

Thank you

**Comment by unfunk77** [comment]
Hi Sandeep,

It was not exactly the same issue. The issue now is the hover effect over the radar chart areas, right? Unfortunately I can't reproduce this untill now.

best regards,
Frank


________________________________
Von: Sandeep Kapalawai <notifications@github.com>
Gesendet: Freitag, 30. Oktober 2020 09:59
An: apexcharts/react-apexcharts <react-apexcharts@noreply.github.com>
Cc: Frank Linhardt <frank.linhardt@qwaiko.de>; Mention <mention@noreply.github.com>
Betreff: Re: [apexcharts/react-apexcharts] create-react-app IE11 Unhandled promise rejection (#137)


Hi @unfunk77<https://github.com/unfunk77> ,

Thanks for the reply , i have tried the same by including in my index.html file. looks like the issue still persists, there was an error in IE 11 ' Unhandled promise rejection TypeError: Unable to get property 'add' of undefined or null reference'

Looks like you went through the same issue , how did you get these resolved.

Thank you
